// data.js
const CarbsOptions = {
  meat: [
    "White Rice",
    "Brown Rice",
    "Quinoa",
    "Barley",
    "Buckwheat",
    "Millet",
    "Oats",
    "Pasta",
    "Sweet Potatoes",
    "Potatoes",
    "Butternut Squash",
    "Corn",
    "Peas",
    "Lentils",
    "Black Beans",
    "Kidney Beans",
    "Chickpeas",
    "Lima Beans",
    "Pinto Beans",
    "Black-Eyed Peas",
    "Green Peas",
    "Soybeans",
    "Edamame",
    "Split Peas",
    "Bread (Whole Wheat)",
    "Bread (Multigrain)",
    "Bread (Rye)",
    "Tortillas (Whole Wheat)",
    "Tortillas (Corn)",
  ],
  vegan: [
    "White Rice",
    "Brown Rice",
    "Quinoa",
    "Barley",
    "Buckwheat",
    "Millet",
    "Oats",
    "Pasta",
    "Sweet Potatoes",
    "Potatoes",
    "Butternut Squash",
    "Corn",
    "Peas",
    "Lentils",
    "Black Beans",
    "Kidney Beans",
    "Chickpeas",
    "Lima Beans",
    "Pinto Beans",
    "Black-Eyed Peas",
    "Green Peas",
    "Soybeans",
    "Edamame",
    "Split Peas",
    "Bread (Whole Wheat)",
    "Bread (Multigrain)",
    "Bread (Rye)",
    "Tortillas (Whole Wheat)",
    "Tortillas (Corn)",
  ],
  vegetarian: [
    "White Rice",
    "Brown Rice",
    "Quinoa",
    "Barley",
    "Buckwheat",
    "Millet",
    "Oats",
    "Pasta",
    "Sweet Potatoes",
    "Potatoes",
    "Butternut Squash",
    "Corn",
    "Peas",
    "Lentils",
    "Black Beans",
    "Kidney Beans",
    "Chickpeas",
    "Lima Beans",
    "Pinto Beans",
    "Black-Eyed Peas",
    "Green Peas",
    "Soybeans",
    "Edamame",
    "Split Peas",
    "Bread (Whole Wheat)",
    "Bread (Multigrain)",
    "Bread (Rye)",
    "Tortillas (Whole Wheat)",
    "Tortillas (Corn)",
  ],
};

export default CarbsOptions;
