// data.js
const proteinOptions = {
  meat: [
    "Avocado",
    "Olive",
    "Almonds",
    "Walnuts",
    "Cashews",
    "Chia",
    "Flaxseeds",
    "Pumpkin",
    "Sunflower",
    "Coconut Oil",
    "Peanut",
    "Butter",
    "Coconut",
    "Flaxseed",
    "Hemp",
    "Sesame",
    "Fish",
    "Edamame",
    "Almond Butter",
    "Peanut Butter",
    "Cashew Butter",
    "Tofu",
    "Olives",
    "Dark Chocolate",
  ],
  vegan: [
    "Avocado",
    "Almonds",
    "Walnuts",
    "Cashews",
    "Pistachios",
    "Chia Seeds",
    "Flaxseeds",
    "Pumpkin Seeds",
    "Sunflower Seeds",
    "Almond Butter",
    "Peanut Butter",
    "Cashew Butter",
    "Coconut Oil",
    "Coconut Milk",
    "Shredded Coconut",
    "Olive Oil",
    "Soybean Oil",
    "Hemp Oil",
    "Flaxseed Oil",
    "Sesame Oil",
  ],
  vegetarian: [
    "Avocado",
    "Dairy Butter",
    "Cheese",
    "Almonds",
    "Walnuts",
    "Cashews",
    "Pistachios",
    "Chia Seeds",
    "Flaxseeds",
    "Pumpkin Seeds",
    "Sunflower Seeds",
    "Almond Butter",
    "Peanut Butter",
    "Cashew Butter",
    "Coconut Oil",
    "Olive Oil",
    "Soybean Oil",
    "Hemp Oil",
    "Flaxseed Oil",
    "Sesame Oil",
  ],
};

export default proteinOptions;
