// data.js
const proteinOptions = {
  meat: [
    "Chicken Breast",
    "Salmon",
    "Eggs",
    "Greek Yogurt",
    "Cottage Cheese",
    "Tofu",
    "Lean Beef",
    "Pork Tenderloin",
    "Turkey Breast",
    "Shrimp",
    "Tuna",
    "Cod",
    "Milk",
    "Cheese",
    "Quinoa",
    "Chickpeas",
    "Lentils",
    "Almonds",
    "Peanuts",
    "Cashews",
    "Chia Seeds",
    "Hemp Seeds",
    "Flax Seeds",
    "Broccoli",
    "Spinach",
    "Brussels Sprouts",
  ],
  vegan: [
    "Lentils",
    "Chickpeas",
    "Tofu",
    "Tempeh",
    "Edamame",
    "Seitan",
    "Quinoa",
    "Soy Milk",
    "Almonds",
    "Peanuts",
    "Cashews",
    "Chia Seeds",
    "Hemp Seeds",
    "Flax Seeds",
    "Spirulina",
    "Nutritional Yeast",
    "Green Peas",
    "Pumpkin Seeds",
    "Black Beans",
    "Kidney Beans",
    "Pinto Beans",
    "Sunflower Seeds",
    "Tahini",
    "Oats",
    "Brown Rice",
    "Soybeans (Roasted or Steamed)",
  ],
  vegetarian: [
    "Beans",
    "Lentils",
    "Chickpeas",
    "Tofu",
    "Tempeh",
    "Edamame",
    "Seitan",
    "Quinoa",
    "Plant-Based Yogurt",
    "Cottage Cheese",
    "Eggs",
    "Almonds",
    "Peanuts",
    "Cashews",
    "Chia",
    "Hemp",
    "Flax",
    "Nutritional Yeast",
    "Spirulina",
    "Hemp Tofu",
    "Green Peas",
    "Pumpkin Seeds",
    "Soy Milk",
    "Amaranth",
    "Soybeans (Roasted or Steamed)",
  ],
};

export default proteinOptions;
